[package]
name = "felidae-admin"
version = "0.2.0"
edition = "2024"

[dependencies]
felidae-types = { path = "../felidae-types" }
thiserror = { workspace = true }
hex = { workspace = true }
tendermint = { workspace = true }
