[package]
name = "felidae-admin"
version = "0.3.2"
edition = "2024"
license.workspace = true

[dependencies]
felidae-types = { path = "../felidae-types" }
thiserror = { workspace = true }
hex = { workspace = true }
tendermint = { workspace = true }
